### ISSUE TITLE
Refused to apply style from <URL> because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled angular

### ISSUE THREAD

**Issue by mehdi-desu** [froala/angular-froala#170]
i got the following issue after installing froala on my angular app.
![froala](https://user-images.githubusercontent.com/28492816/36342932-504d4196-13ba-11e8-9d08-2a1b61f930c5.PNG)

it's not applying the style for some reason :
![froalastyle](https://user-images.githubusercontent.com/28492816/36342987-e92b73c4-13ba-11e8-8b2c-940244383ead.PNG)
any ideas please ?

**Comment by stefanneculai** [comment]
@mehdi-desu it looks like the CSS files are loaded as HTML instead of Stylesheets. It appears to be something like this: https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type.

**Comment by craigpearson** [comment]
As this shows up a lot in Google Search results I thought I'd share that in similar projects this appears to be due to the inclusion of HBP5 directives for Nginx.

If the extra security file below is included, then stylesheets being served through proxies such as webpack will fail to load due to CSP. See the notes on Line 17 below

https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/extra-security.conf

Although this setting has been in HBP5 configs for a while, webkit browsers have only just started enforcing it. Hope this helps others

**Comment by NikolaiYurchenko** [comment]
ya loh

**Comment by Jeeva-Rathinam** [comment]
@mehdi-desu did you solve your issue?

**Comment by alanducnguyen** [comment]
I had the same issue in PHP. Then i solved it after changing the permission of the directory to 755 to allow the file has the access right.

**Comment by amrsalem87** [comment]
Having same issue 
Refused to apply style from...styles.f4fb5cb8ad4ea5bce7fb.bundle.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by connect2amitu** [comment]
Apply this base tag **<base href="/">**
after title tag in index.html

**Comment by connect2amitu** [comment]
![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)

**Comment by dharmmaurya563** [comment]
http://prntscr.com/jecsmv

**Comment by hgsigner** [comment]
@connect2amitu you saved my day here :) I was having this problem with react and react router running with webpack-dev-server and `<base href="/">` does the trick.

**Comment by mart1n8891** [comment]
Depending on which angular/webpack version you use:
Have you tried setting "styles" and "scripts" in the .angular-cli.json (or angular.json for angular 6+) instead of the index.html file? E.g. "styles": [ "node_modules/.../...css", "..." ], "scripts": [ "node_modules/.../...js", "..."], ...

**Comment by vanoMekantsishvili** [comment]
@connect2amitu <base href="/"> this trick actually works for me too but can you explain how this thing works? thank you : )

**Comment by DaoFof** [comment]
@connect2amitu  it doesn't work for me

**Comment by claudz1** [comment]
@connect2amitu this trick worked ,thanks a lot!

**Comment by frempongandrews** [comment]
<base href="/"> 
Worked for me, thanks!!

**Comment by krasicji** [comment]
I think the root cause of the issue is that the minified css has comments in them. Check out https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type

**Comment by atinyakov** [comment]
> I think the root cause of the issue is that the minified css has comments in them
minified css does not contain comments.

I have faced the issue as well, in my case, the css file was missing, but defined in HTML

**Comment by sudiptosen** [comment]
I do not think that the content of the `css` matters. For example, in my `index.html`, I tried replacing the Material Icons css with a local version as follows:

`  

  <link rel="stylesheet" type="text/css" href="google_material.css">
`
I get the same error when the `google_material.css` is blank!

**Comment by arduino731** [comment]
I was using Node npm module on my project without angular frameworks. I m using Embedded JavaScript templates (EJS). I added new folders and it keeps showing error loaded of CSS style and js files, so I have decided to put into head.html 
`<base href="/"`
Those are solved problems. thank you!

**Comment by 3nraged** [comment]
Having the same issue currently.

**Comment by SuyogABankar** [comment]
i have same issue .i have tried this much but still img is not getting load.what should i do?

                  
                  <img src="/suyog.jpg" alt="suyog" class="img-fluid">

**Comment by SuyogABankar** [comment]
i have saved photo in c folder.how to give path?

**Comment by TheSLX** [comment]
Not sure if this will help anyone, but if you are using angular-cli, I fixed this by removing the css reference from my index into the angular-cli.json file under the "style" portion.
After restarting my webserver I no longer had that issue.

**Comment by Rich0101** [comment]
Adding <base href="/"> before linking the stylesheets didn't work for me, but taking the rel property of the  <link> tag did work:

<link rel="stylesheet" href="styles.css" type="text/css">     produced the error

<link href="styles.css" type="text/css">      No error

**Comment by ovidiup13** [comment]
@Rich0101 The error disappears but the styles are not applied unfortunately :confused:

**Comment by Piligrim25** [comment]
Just add type="text/html"
Like this <link rel="stylesheet" href="css/style.css" type="text/html">

**Comment by keeve** [comment]
@Rich0101  your trick works for me, even with comments in my css. 

@ovidiup13 debug your page in chrome, probably there's a css overriding your style. 
I'm using Angular Material and I wanted to make the button's font smaller, so what I did is explicitly have css for the entire body and manipulate mat-button like this 

.body-container .mat-button {
    font-size: small !important;
}

It works :)

**Comment by arshad115** [comment]
@connect2amitu `<base href="/">` also didn't work for me. 
@Rich0101  solution worked by removing the stylesheet property and adding `type="text/html"` in the link tag.

**Comment by ulrichdohou** [comment]
Tks @connect2amitu it works fine

**Comment by pathum-kalhan** [comment]
Errors and solutions are weird sometimes.
What worked for me is  keep ` rel="stylesheet"` and additionally add the `type="text/css"` also `<base href="/">` would not worked for me.

**Comment by gladtobhere** [comment]
I had this same prob. My folder structure wasn't right.  Some how I created my "css" folder inside my "scripts folder".  Double check your folder structure.  Worked for me.

**Comment by pshoultz** [comment]
have the same error and these solutions aren't working

**Comment by piliugin** [comment]
In my case the problem was that webpack-dev-server returns text: "Cannot GET /dist/css/index.css".
So check that files exists.
Similar problem with js: https://github.com/webpack/webpack/issues/3027

**Comment by raulra08** [comment]
This helped me,
https://blog.angularindepth.com/this-is-how-angular-cli-webpack-delivers-your-css-styles-to-the-client-d4adf15c4975

To realise that styles.css becomes styles.js, and therefore it should be included as a script at the bottom of the body rather than at the head as a link.

**Comment by wisedip** [comment]
Checking my file-Url helped me. Errors in your Url input is the main problem. Check whether you have included a static file to connect the view files to the query.
Recheck it. It took me almost 2 hours to find the Error in the Url

**Comment by ming0627** [comment]
Im using MiniCssExtractPlugin and i realized missing '**.**' will caused below issue.

from

    filename: '/style.[contenthash].css'
to

    filename: './style.[contenthash].css'





//correct way should be like this

    new MiniCssExtractPlugin({
      publicPath: './sass/',
      filename: './style.[contenthash].css'
    });



Hope this help you.

**Comment by AvinashMV** [comment]
<base href="/"> solved my issue. Thanks man!

**Comment by Avi308** [comment]
@connect2amitu  Thank you :)

**Comment by akshaymittal143** [comment]
<base href="/"> worked for me as well. Thanks

**Comment by shahramverb** [comment]
![image](https://user-images.githubusercontent.com/32303266/45930528-63133d80-bf59-11e8-9a58-d0043d062512.png) 

adding <base href="/"> before my link tags fixed my issue hope this helps others

**Comment by ujikit** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/">` in head before linking all css files

nice trick (y), working like a charm.

**Comment by errepy** [comment]
ajaa install globally please don't try the easy way... on angular.json in style use: 
{
"input": "your url"
}
for every javascript you need to add to your project

**Comment by ngl4** [comment]
> Adding `<base href="/">` before linking the stylesheets didn't work for me, but taking the rel property off the `<link>` tag did work:
> 
> ```
>   <link rel="stylesheet" href="styles.css" type="text/css">     Produces Error
> 
>   <link href="styles.css" type="text/css">      No error
> ```

This works for me!!! Thanks a lot!!!

**Comment by emilalsgndr** [comment]
> > ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> > Add `<base href="/">` in head before linking all css files
> 
> nice trick (y), working like a charm.

thans its work for me (gulpjs)

**Comment by yeasin-Ahammed-apon** [comment]
<base href="/"> it is working fine for me . thanx

**Comment by yeasin-Ahammed-apon** [comment]
"<base href="/">"  is working fine for me . thank you.

**Comment by yonatanLehman** [comment]
The <base href="/"> didn't work for me.
My problem was  that the path to the file was in mixed lower and uppercase and the actual folder structure was in lowercase. My local machine is windows and the actual site is on a Heroku server which seems to be Linux.  Also renaming my local folder to match the case of the link didn't to work, since in Git renaming a folder (and I suppose file) does not get passed on. I had to copy the folder aside, delete the original folder, git commit, git push, and then recreate the folder and commit and push again.

**Comment by krishnavaddepally** [comment]
Okay! so I changed type="text/css" instead of html. 
it worked.

**Comment by johnybravo123** [comment]
> Adding `<base href="/">` before linking the stylesheets didn't work for me, but taking the rel property off the `<link>` tag did work:
> 
> ```
>   <link rel="stylesheet" href="styles.css" type="text/css">     Produces Error
> 
>   <link href="styles.css" type="text/css">      No error
> ```

does the job for me

**Comment by vigneshikl** [comment]
> Adding `<base href="/">` before linking the stylesheets didn't work for me, but taking the rel property off the `<link>` tag did work:
> 
> ```
>   <link rel="stylesheet" href="styles.css" type="text/css">     Produces Error
> 
>   <link href="styles.css" type="text/css">      No error
> ```

Perfect! It works!

**Comment by hendisantika** [comment]
It's not working for me.
I don't know why.

<img width="1440" alt="Screen Shot 2019-04-12 at 08 18 09" src="https://user-images.githubusercontent.com/3713580/56005621-8a660800-5cfb-11e9-8bd6-73ac01a4c249.png">

**Comment by vigneshikl** [comment]
Can you please share the file references ? @hendisantika

**Comment by hendisantika** [comment]
Sorry, I misunderstood. My project is using Spring Boot not angular. But, I has same issue. Is it still related?

**Comment by vigneshikl** [comment]
I am not sure, but still wherever you have CSS file reference in your code. Try removing **rel="Stylesheet"**

**Comment by dollyshah-02** [comment]
removing rel attribute and adding type="text/html" removed my error.But it is not applying my styles.

**Comment by vigneshikl** [comment]
@dollyshah-02 It should be **type="text/css"**. Isn't?

**Comment by Megas97** [comment]
@connect2amitu I had the same error but for 'application/json' type and weirdly not on all pages. Wasn't using Angular but your trick still fixed it for me as well. Thanks a lot :)

**Comment by saamtehraani** [comment]
I had the same error, I noticed that I have referenced font-awesome to wrong css file in angular.json file. 

In fact references in angular.json and <head></head> should be the same.

I made them the same and the problem solved.

![image](https://user-images.githubusercontent.com/3000791/57414793-faa17400-723c-11e9-8c8c-220d8ff275d6.png)
![image](https://user-images.githubusercontent.com/3000791/57414805-02f9af00-723d-11e9-95b6-d99a0df4c749.png)

**Comment by franciscosuca** [comment]
> Just add type="text/html"
> Like this

This worked for me on Vue js 2. Thanks a lot!

**Comment by AJW86** [comment]
Hi guys,

I'm not sure if this will help anyone. As it's take me three days to figure out. None of the above worked for me but this instead of using <base href="/"> Im working with node sass.

dist
  css
  img
  js
scss

href="dist/css/main.css" 
             ^

i added an extra path at the beginning

**Comment by gada121982** [comment]
connect2amitu  it work for me :v. thanks you 🥉

**Comment by loganlokku** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

thanks a lot love uuuuuuu

**Comment by chr1s1k** [comment]
I had exactly the same issue and solution was pretty easy => I had wrong path to my CSS file.

I had

`<link rel="stylesheet" type="text/css" href="/css/style.css" />`

instead of

`<link rel="stylesheet" type="text/css" href="/public/css/style.css" />`

Because my project structure is following:

![image](https://user-images.githubusercontent.com/1590635/65491375-3a48bf80-deaf-11e9-9b26-7fb4cadeedc6.png)

**Comment by bphilipnyc** [comment]
I found this due to the `@` symbol in the folder name.  Once I renamed the folder, the problem went away.  Adding the base href didn't work.  I opened up a question SO about it:

https://stackoverflow.com/questions/58635585/how-do-i-escape-an-character-in-a-thymeleaf-link-tag/58637963#58637963

**Comment by naveen1416** [comment]
Same issue for me, but there is no Error showing in the console.. :-(

**Comment by jasmineibikunle1** [comment]
I had this issue and it was caused by having the wrong file path.

**Comment by skarakash** [comment]
![2019-12-26 23_44_14-D__Projects_Task_views_jsx_main jsx (Task) - Sublime Text (UNREGISTERED)](https://user-images.githubusercontent.com/11464117/71491494-ad106080-2839-11ea-8aac-5c8104cfdbf3.png)
still don't quite understand how this worked but, 
`<link rel="stylesheet" type="text/css" href="base.css"/>` did the trick. whil I was stubbornly trying to put it  href="css/base.css"

**Comment by Mat-Longinow** [comment]
If anyone is here from Pug (with Node.js/Express), here is what worked for me:

In my view .pug file, use their built in `include` (docs [here](https://pugjs.org/language/includes.html))

![Screen Shot 2020-01-24 at 2 54 55 PM](https://user-images.githubusercontent.com/6404079/73109937-86395e80-3eb9-11ea-920c-e00d9936fbab.png)

**Comment by sarfraznawaz2005** [comment]
in my case it was file/folder permission issue.

**Comment by kikeflowers** [comment]
@connect2amitu  THANKS A LOT! You saved me hours of research.

**Comment by Trovidan** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

this surely does the trick! thanks a lot dude

**Comment by sagarPakhrin** [comment]
> Adding `<base href="/">` before linking the stylesheets didn't work for me, but taking the rel property off the `<link>` tag did work:
> 
> ```
>   <link rel="stylesheet" href="styles.css" type="text/css">     Produces Error
> 
>   <link href="styles.css" type="text/css">      No error
> ```

This worked for me.

**Comment by isuruwelagedara** [comment]
make new CSS folder inside the assets folder then put your CSS file inside CSS folder then link again with the new location 

`Eg : -  <link rel="stylesheet" href="assets/css/materialize.min.css"> `

**Comment by facundoA2** [comment]
> > Adding `<base href="/">` before linking the stylesheets didn't work for me, but taking the rel property off the `<link>` tag did work:
> > ```
> >   <link rel="stylesheet" href="styles.css" type="text/css">     Produces Error
> > 
> >   <link href="styles.css" type="text/css">      No error
> > ```
> 
> This worked for me.

This worked for me too

**Comment by Luis0lo** [comment]
> The didn't work for me.
> My problem was that the path to the file was in mixed lower and uppercase and the actual folder structure was in lowercase. My local machine is windows and the actual site is on a Heroku server which seems to be Linux. Also renaming my local folder to match the case of the link didn't to work, since in Git renaming a folder (and I suppose file) does not get passed on. I had to copy the folder aside, delete the original folder, git commit, git push, and then recreate the folder and commit and push again.

**Comment by AlaEddineLaouir** [comment]
@connect2amitu  Thank you, it worked

**Comment by soumyarout** [comment]
`"styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              },
              {
                "input": "src/app/app.scss"
              },
              **{
                "input": "node_modules/froala-editor/css/froala_editor.pkgd.min.css"
              }**
            ]`

Instead of adding in index.html add css for in `angular.json` and re-run `ng s `

**Comment by NikhilRajivOke** [comment]
Hi, all the above solutions didn't work for me. So just putting my code snippets out there, so that I can get some help. Spend more than 2 days just figuring out the issue.

so I am using angular 8 and installed owl-carousel using npm command
and after that linking the CSS file is getting me a lot of pain.

so this is my file structure in node modules
![image](https://user-images.githubusercontent.com/60400160/82088859-2688ec80-9710-11ea-9774-0480b367ea67.png)

so this is my index.html
![image](https://user-images.githubusercontent.com/60400160/82089015-694ac480-9710-11ea-83e6-5fc0c6051ab1.png)

so when I remove the rel attribute the error is resolved but still, the styles are not applied.

errors displayed in the console
![image](https://user-images.githubusercontent.com/60400160/82089207-d2323c80-9710-11ea-945a-b697bf651fcd.png)

Kindly help me pls! stuck here for a long time......

**Comment by dnldpavlik** [comment]
I am seeing this error as well, the only way I was able to get around it was to disable the strict mode enabling in the ts config file. I am fine with turning this off in development as I will not be the webserver that angular is using for development deploy my site, rather it will be IIS.

  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": false
  }
}

**Comment by Vishwanath20** [comment]
I had same issue, i restarted the server and looks like my application is working fine.

**Comment by mliling** [comment]
@dnldpavlik It still doesn't work.

**Comment by dnldpavlik** [comment]
Did you restart the server after you made the change? After made the update
to the config file I restarted the server and it is working for me.

Also, I am running this on Windows 10, with node installed on Windows, not
through a container or via WSL.

**Comment by abdeldjalilhachimi** [comment]
`<base href="/"> 
worked for me try it out 

Thanks for the brilliant trick `

**Comment by Chapulex** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

i don't know who you are but u save my life man, Thanks so Much!

**Comment by RathoreRijhu** [comment]
I have angular material used in my angular project it is working fine on local but not working in production mode over aws instance .
what can be the issue?

**Comment by diAgo-44** [comment]
> @connect2amitu you saved my day here :) I was having this problem with react and react router running with webpack-dev-server and `<base href="/">` does the trick.

Heys guys i also faced the same issue but found the exact solution for this.

So css ,images ,etc are static files,if we try connecting css files using link it will cause MIME Error.
Express serves them using Built in static function.
Move all your assets into one folder, i named that folder public.

So just use this line: app.use(express.static('public'));
It allows us to access static files and use them without causing an error.

consider the folder structure:-
public
-- style.css
--images
-----img1.jpeg
-----img2.jpeg

Now normally i would link style.css like this:
<link rel="stylesheet" href="public/style.css" type="text/css">    ==> This will again cause an error

Here:- app.use(express.static('public'));  We are passing the public folder , now to access the style.css use relative path like this

<link rel="stylesheet" href="./style.css" type="text/css">


IT WORKS PERFECTLY, i spent a while to find this solution.

**Comment by vimalkuriensam** [comment]
In my case, I was using a react application created using webpack. I implemented the 7-1 architecture in Saas, but forgot to import the main.scss file into my app.js. So my inference is that when the css path is given in the index.html file but there ain't a css import, this error will pop up.

**Comment by newbie-but-trying** [comment]
> > @connect2amitu you saved my day here :) I was having this problem with react and react router running with webpack-dev-server and `<base href="/">` does the trick.
> 
> Heys guys i also faced the same issue but found the exact solution for this.
> 
> So css ,images ,etc are static files,if we try connecting css files using link it will cause MIME Error.
> Express serves them using Built in static function.
> Move all your assets into one folder, i named that folder public.
> 
> So just use this line: ` app.use(express.static('public'));`
> It allows us to access static files and use them without causing an error.
> 
> consider the folder structure:-
> public
> -- style.css
> --images
> -----img1.jpeg
> -----img2.jpeg
> 
> Now normally i would link style.css like this:
> `<link rel="stylesheet" href="public/style.css" type="text/css">` ==> This will again cause an error
> 
> Here:-` app.use(express.static('public'));` We are passing the public folder , now to access the style.css, use relative path(its relative to public )but like this
> 
> `<link rel="stylesheet" href="./style.css" type="text/css">`
> 
> IT WORKS PERFECTLY, i spent a while to find this solution.

This should be upvoted way more. Solved my problem instantly with logical solution. Spent hours searching on google.
I am also using Express and was just the tiny addition of "./" in path to solve headache. Thank you!

**Comment by holdermatthew5** [comment]
@vanoMekantsishvili The <base href="/"> is most likely a command telling the browser that every path in this file should have a / placed in front of it. So if I put a path "styles/base.css" the browser will read it as "/styles/base.css". This could be a real pain if you don't know this because if you try to use the path "/styles/base.css" the browser will read it as "//styles/base.css". I'm currently attending code fellows and the way we set this feature was in our js file with the line "app.use(express.static('./public'));" where express is a dependency and app is an instance of express (e.g. const app = express();). With that line every path will be read as starting with "./public" so "styles/base.css" would be read as "./public/styles/css". It comes in handy when you have a large file structure and most of the files you need are in the same folder/directory.

**Comment by yannickbaze** [comment]
thank you soo much  @diAgo-44 , i had this issue on express,
but this solution is super and just saved me from a lot of headache.
first: i used the the: app.use(express.static('assets')
note that app is my server object created using express function
let app = express
second: i created a folder and named it assets( in which i put all my assets, like css, img, video etc)
third: I created my link in html like as follows:
<link rel="stylesheet" type="type/css" href="./css/style.css">

note that i omitted assets in my path....

**Comment by edutime** [comment]
This issue can also occur if there is/are #, $ and @ in the folder name. Removing them can solve the issue.

**Comment by Toan2671997** [comment]
> Adding `<base href="/">` before linking the stylesheets didn't work for me, but taking the rel property off the `<link>` tag did work:
> 
> ```
>   <link rel="stylesheet" href="styles.css" type="text/css">     Produces Error
> 
>   <link href="styles.css" type="text/css">      No error
> ```

Lol, this is work for me.

**Comment by Prashant-21** [comment]
Note: If you are using <base href="/" /> then you should use relative path instead of absolute. 

    <link rel="stylesheet" href="./styles/index.css" type="text/css" />
This worked in my case.

**Comment by abhishekdwaghmare2000** [comment]
I am trying to create a template .but,css is not loading.
![IMG_20210203_211409](https://user-images.githubusercontent.com/67356851/106771720-47f68380-6665-11eb-8b6b-09a85420b7ec.jpg)
kindly,please help me.I tried all the above trick but still stuck in te same error   "Refused to apply style from 'http://localhost:3000/public/css/styles.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

index.html  file :- 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/image/logo.png">
    <link rel="stylesheet" type="text/css" href="/public/css/styles.css">
    <title>Main</title>
</head>
<body>
    <p>Web</p>
</body>
</html>


styles.css file :-


body {
    background-color: darkred;
}

p {
    color: darkred;
    size: 300px;
}

**Comment by VishnuKrishnathu** [comment]
For me, the mime type error was caused by Heroku as it was unable to detect the static files. All you have to do is to add a middleware of white noise. ( whitenoise.evans.io/en/stable )

**Comment by Ajaydevsysart** [comment]
<base href="/">
Worked for me, thanks

**Comment by Ajaydevsysart** [comment]
<base href="/">
Worked for me, thanks!!

**Comment by rohini-hansda** [comment]
thank you..it's worked for me

**Comment by heD0ng** [comment]
actually, you need an absolute path like '/public/main.css'. Moreover, you need take care of  'express.static(__dirname+ '/public').

**Comment by devtech92** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

This one has solved my issues. Thank you.

**Comment by Alimba86** [comment]
Not on React, but Drupal 8, I had the same issue. What solved the issue was to remove any comments from the minified version of my CSS.

**Comment by thinhquocle** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files
This one did solve my issues, thank you.

**Comment by petatemarvin26** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

**NOT WORKING**
`<link href="./static/css/main.4d0d053f.chunk.css" rel="stylesheet" />`

**WORKING** 
`<link href="../static/css/main.4d0d053f.chunk.css" rel="stylesheet" />`

**PROBLEM**
The question here is, why html did not read the absolute path even it is correct absolutely on his location, is it bug?

**Comment by petatemarvin26** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

**NOT WORKING**
`<link href="./static/css/main.4d0d053f.chunk.css" rel="stylesheet" />`

**WORKING** 
`<link href="../static/css/main.4d0d053f.chunk.css" rel="stylesheet" />`
this is also working without `<base href="/"/>`

**PROBLEM**
The question here is, why html did not read the absolute path even it is correct absolutely on its location, is it bug?

**Comment by veer-vikram** [comment]
i also had the same problem : here is the solution, don't write **public** in path of image in your .html file. although your image file present in the public folder.

example:- **js file**

`app.use(express.static("public"));`
**html file use this**

`<img  src="Icon.png">`
**instead of**

`<img  src="index/Icon.png">`

**Comment by rameshmarandi** [comment]
> > @connect2amitu you saved my day here :) I was having this problem with react and react router running with webpack-dev-server and `<base href="/">` does the trick.
> 
> Heys guys i also faced the same issue but found the exact solution for this.
> 
> So css ,images ,etc are static files,if we try connecting css files using link it will cause MIME Error.
> Express serves them using Built in static function.
> Move all your assets into one folder, i named that folder public.
> 
> So just use this line: ` app.use(express.static('public'));`
> It allows us to access static files and use them without causing an error.
> 
> consider the folder structure:-
> public
> -- style.css
> --images
> -----img1.jpeg
> -----img2.jpeg
> 
> Now normally i would link style.css like this:
> `<link rel="stylesheet" href="public/style.css" type="text/css">` ==> This will again cause an error
> 
> Here:-` app.use(express.static('public'));` We are passing the public folder , now to access the style.css, use relative path(its relative to public )but like this
> 
> `<link rel="stylesheet" href="./style.css" type="text/css">`
> 
> IT WORKS PERFECTLY, i spent a while to find this solution.

Thanks buddy, It helps me to this post . This method is worked for me .

**Comment by eddskt** [comment]
> Não tenho certeza se isso vai ajudar alguém, mas se você estiver usando o angular-cli, resolvi isso removendo a referência css do meu index.html e adicionando-a ao arquivo angular-cli.json na parte "estilo".
> Depois de reiniciar meu servidor web, não tive mais esse problema.



> Not sure if this will help anyone, but if you are using angular-cli, I fixed this by removing the css reference from my index.html and adding it to the angular-cli.json file under the "style" portion.
> After restarting my webserver I no longer had that issue.

this works, thanks, for angular-cli this is the only viable and logical solution, as it is part of their process to add any stylesheet to angular.json, as well as bootstrap and other tools.

**Comment by vancouver29** [comment]
> As this shows up a lot in Google Search results I thought I'd share that in similar projects this appears to be due to the inclusion of HBP5 directives for Nginx.
> 
> If the extra security file below is included, then stylesheets being served through proxies such as webpack will fail to load due to CSP. See the notes on Line 17 below
> 
> https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/extra-security.conf
> 
> Although this setting has been in HBP5 configs for a while, webkit browsers have only just started enforcing it. Hope this helps others

your link is died !

**Comment by LakshmiMishra** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

This worked for me.Thanks

**Comment by mcmonojit** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

Thank You so much :) . This solved my problem.

**Comment by JotaErrE01** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

Thanks bro, it worked. uwu

**Comment by gurjeetsinghvirdee** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

@connect2amitu Thanks man, It worked!

**Comment by tshering-sherpa** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png)
> Add `<base href="/"> ` in head before linking all css files

Not sure why that is, but it definitely fixed the CSS issue .Thanks

**Comment by tanvirstreame** [comment]
If you are using core ui dashboard

just remove "homepage": "." 

from  package.json

**Comment by danimomoh** [comment]
> I had exactly the same issue and solution was pretty easy => I had wrong path to my CSS file.
> 
> I had
> 
> `<link rel="stylesheet" type="text/css" href="/css/style.css" />`
> 
> instead of
> 
> `<link rel="stylesheet" type="text/css" href="/public/css/style.css" />`
> 
> Because my project structure is following:
> 
> ![image](https://user-images.githubusercontent.com/1590635/65491375-3a48bf80-deaf-11e9-9b26-7fb4cadeedc6.png)


This incorrect path issue worked for me. Thanks

**Comment by vaibhav-a-porwal** [comment]
> 

Dang! this does the trick.....
Thanks a lot.

**Comment by sachintha49** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png) Add `<base href="/"> ` in head before linking all css files

Thank you.

**Comment by Roto1707** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png) Add `<base href="/"> ` in head before linking all css files

Thank you. It work for me

**Comment by Izurays** [comment]
For express app
app.use(express.static(path.join(__dirname, "public")));
use .ejs instead of .html in res.render()
create a public folder and store your files and sytles there

**Comment by gvasudha003** [comment]
@ovidiup13 is your problem solved I have same problem.

**Comment by gvasudha003** [comment]
> app.use(express.static("public"));

I works but unfortunately css is not applied

**Comment by LautaroLorenz** [comment]
same problem with ElectronJs and AngularJs if url has a param like:

```
const routes: Routes = [{
    path: 'editar-template-ensayo/:id',
    component: EssayTemplateBuilderComponent
}]
```

After page reload

![image](https://user-images.githubusercontent.com/21241657/175797740-9e916b23-8459-4f93-b94d-3e528c2984df.png)

**Comment by shankar55** [comment]
Hi guys,
while learning Dapps i have faced this error i am unable to load image and css styles to the browser.
![image](https://user-images.githubusercontent.com/41586715/181934518-f094b9f8-971c-4d92-b1df-44b2caa1e0d2.png)
![image](https://user-images.githubusercontent.com/41586715/181934529-1f0d7d32-c6f1-403c-9981-6473de5aae88.png)
In the above image i am unable to load the image i hav tried lot if any one have the solution pls share it

**Comment by shankar55** [comment]
i am doing the project from wsl in windows

**Comment by franzwcom** [comment]
it needs to mount the folder where the css files are ...
`"storybook": "cross-env NODE_ENV=development start-storybook -s ./dist -p 6006",`

**Comment by jerlabor** [comment]
adding this  line of code to my nginx server solved my problem

```
# Include MIME Types
include /etc/nginx/mime.types
```

**Comment by Jomedi** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png) Add `<base href="/"> ` in head before linking all css files

MAANNNN YOU SAVED MY PROEJCTT!!!! THANKSSSS VERY MUCHHH

**Comment by mohammedjodi** [comment]
none of this ones worked for me please if you have the solution please share with me

**Comment by Eunit99** [comment]
Adding `<base href="/">` in `public/index.html` in my React application solved the issue for me as well.

![solved](https://user-images.githubusercontent.com/24845008/207390594-0a3bdacf-4f88-4e19-be32-0aba0e822317.png)

**Comment by abhisheksurela79** [comment]
Could you please explain the purpose of the `<base href="/">` tag? I encountered the same MIME error in my Django app, and using this tag helped resolve the issue, but I am not sure why it was effective. Could you provide some insight into how it functions in this context?

**Comment by makan-dianka** [comment]
if you are using django, you may forget to install whitenoise when debug turn off.

`pip install whitenoise`

then append this into middleware variables in the settings file

`"whitenoise.middleware.WhiteNoiseMiddleware",`

**Comment by Davidchanz** [comment]
If you write on Spring, maybe problem with security, you cannot get access to any files include css and js while you are not login
![image](https://user-images.githubusercontent.com/92250001/229284922-6692fcf9-8344-4231-bae9-2983650f3f91.png)

**Comment by paaatcha** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png) Add `<base href="/"> ` in head before linking all css files

Thanks, man! It solved my problem! <3

**Comment by jeorlie** [comment]
gulp was not installed on mine. so running "npm install yarn --force" did the trick.

**Comment by mikegyamfi** [comment]
> if you are using django, you may forget to install whitenoise when debug turn off.
> 
> `pip install whitenoise`
> 
> then append this into middleware variables in the settings file
> 
> `"whitenoise.middleware.WhiteNoiseMiddleware",`

Thanks a lot. That did the trick for me. Bless you.

**Comment by buiphihien24032001** [comment]
> If you write on Spring, maybe problem with security, you cannot get access to any files include css and js while you are not login ![image](https://user-images.githubusercontent.com/92250001/229284922-6692fcf9-8344-4231-bae9-2983650f3f91.png)
> 
> Made like on Image "/styles/**" - is directory with all your CSS. "/scripts/**" - is directory with all your JavaScript.

Hi bro. Thank you very much. Your solution has solved my problem.

**Comment by Galigao07** [comment]
if you are using django, you may forget to install whitenoise when debug turn off.

pip install whitenoise

then append this into middleware variables in the settings file

"whitenoise.middleware.WhiteNoiseMiddleware", 


YOUR MY LIFE SAVER THANK YOU VERY VERY MUCH..

**Comment by NikYurchik** [comment]
> if you are using django, you may forget to install whitenoise when debug turn off.
> `pip install whitenoise`
> then append this into middleware variables in the settings file
> `"whitenoise.middleware.WhiteNoiseMiddleware",`
Thank you! It helped me too.

**Comment by hossam43** [comment]
Just create a 'public' directory and place all your static files and folders inside it.

**Comment by ronydv** [comment]
was facing

> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png) Add `<base href="/"> ` in head before linking all css files

works perfectly!!!! thanks a lot man, was facing this issue doing react app with spring boot but that tiny tag seems to be super important, thanks so much!!

**Comment by peixiaotan1** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png) Add `<base href="/"> ` in head before linking all css files

I fixed it, but I don't understand why.

**Comment by kapil26021994** [comment]
Hi @connect2amitu  I have tried your solution but still not resolved can you tell me any another solution?

**Comment by AMilinovic0801** [comment]
So if anyone is still struggling what worked for me was the following: my links were written like ../web-shop/css-sytle/style.css and the server would not for the life of me find these links. They worked fine directly from the HTML file. What I had to do is write it /web-shop/css-style/style.css. And that worked like a charm. Man I lost 5 days on this.

**Comment by ooyanpaing222** [comment]
change style.css to index.css. it will solve.

**Comment by SEA6153** [comment]
Hi guys, i'm using spring boot and tried all thing what you write but nothing happens. Could you help me please? 
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org"  xmlns:sec="http://www.thymeleaf.org/extras/spring-security"  lang="en" >
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link th:href="@{/css/body.css}"  type="text/css"/>
    <link th:href="@{/css/footer_specialtoform.css}" type="text/css"/>
    <link th:href="@{/css/footerimp.css}"  type="text/css" />
    <link th:href="@{/css/header.css}" type="text/css"/>
This is one of my HTML file,
@Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .authorizeRequests()
                .antMatchers(WHITELIST).permitAll()
                .antMatchers(HttpMethod.GET, "/posts/*").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin()
                .loginPage("/login")
                .loginProcessingUrl("/login")
                .defaultSuccessUrl("/", true)
                .failureUrl("/login?error").permitAll()
                .and()
                .logout()
                .logoutUrl("/logout")
                .logoutSuccessUrl("/login?logout")
                .and()
                .httpBasic();

        return http.build();
    } 
This is my SecurityConfig class.

**Comment by SEA6153** [comment]
Hi guys, i'm using spring boot and tried all thing what you write but nothing happens. Could you help me please?

This is my HTML 
`<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org"  xmlns:sec="http://www.thymeleaf.org/extras/spring-security"  lang="en" >
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link th:href="@{/css/body.css}"  type="text/css"/>
    <link th:href="@{/css/footer_specialtoform.css}" type="text/css"/>
    <link th:href="@{/css/footerimp.css}"  type="text/css" />
    <link th:href="@{/css/header.css}" type="text/css"/>`


This is my SecurityConfig class


`    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .authorizeRequests()
                .antMatchers(WHITELIST).permitAll()
                .antMatchers(HttpMethod.GET, "/posts/*").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin()
                .loginPage("/login")
                .loginProcessingUrl("/login")
                .defaultSuccessUrl("/", true)
                .failureUrl("/login?error").permitAll()
                .and()
                .logout()
                .logoutUrl("/logout")
                .logoutSuccessUrl("/login?logout")
                .and()
                .httpBasic();

        return http.build();
    }`

**Comment by SEA6153** [comment]
Hi guys, i'm using spring boot and tried all thing what you write but nothing happens. Could you help me please?

This is my HTML


`<html xmlns:th="http://www.thymeleaf.org"  xmlns:sec="http://www.thymeleaf.org/extras/spring-security"  lang="en" >
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link th:href="@{/css/body.css}"  type="text/css"/>
    <link th:href="@{/css/footer_specialtoform.css}" type="text/css"/>
    <link th:href="@{/css/footerimp.css}"  type="text/css" />
    <link th:href="@{/css/header.css}" type="text/css"/>`



This is my Security Config class

`    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .authorizeRequests()
                .antMatchers(WHITELIST).permitAll()
                .antMatchers(HttpMethod.GET, "/posts/*").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin()
                .loginPage("/login")
                .loginProcessingUrl("/login")
                .defaultSuccessUrl("/", true)
                .failureUrl("/login?error").permitAll()
                .and()
                .logout()
                .logoutUrl("/logout")
                .logoutSuccessUrl("/login?logout")
                .and()
                .httpBasic();

        return http.build();
    }`

**Comment by SEA6153** [comment]
Hi guys, I'm using Spring Boot - Thymeleaf and I tried all thing what you write but nothing happened. Thymeleaf or IntelliJ(I don't know which one is) doesn't see my CSS files. Could you help me please?

These are my codes.

![html1](https://github.com/froala/angular-froala/assets/108074970/afe2470f-c8d7-454e-88db-70190992aa1d)




![1sec](https://github.com/froala/angular-froala/assets/108074970/0e83d31b-3209-47ae-b789-94f23753447d)

**Comment by juara-digital** [comment]
> ![image](https://user-images.githubusercontent.com/36689910/39548702-052c262e-4e79-11e8-8c4d-5fa9ec08a22f.png) Add `<base href="/"> ` in head before linking all css files

This is worked for me, thanks 😁
